# Traz todos os servidores
GET http://localhost:3000/servers
Content-Type: application/json

###
# Insere novo servidor
POST http://localhost:3000/servers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJsdWNhc0BzZXJ2aWNldHJpeC5jb20iLCJuYW1lIjoibHVjYXMiLCJpYXQiOjE2MTYwMjkwMjIsImV4cCI6MTYxNjAzOTgyMn0.pvQ1-Srznc-37it8JJlyDiaGITDShZCg08bpGRj0A5g
{
    "name": "teste-04",
    "ip": "192.168.0.4"
}
###
# ALTERA UM SERVIDOR
PATCH  http://localhost:3000/servers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJsdWNhc0BzZXJ2aWNldHJpeC5jb20iLCJuYW1lIjoibHVjYXMiLCJpYXQiOjE2MTYwMjkwMjIsImV4cCI6MTYxNjAzOTgyMn0.pvQ1-Srznc-37it8JJlyDiaGITDShZCg08bpGRj0A5g
{
    "name": "teste-04",
    "ip": "192.168.0.4",
    "id": "1"
}
###
# DELETA UM SERVIDOR
DELETE http://localhost:3000/servers/
Content-Type: application/json
{
    "id": "1"
}
###
# TRAZ DADOS DE UM SERVIDOR
GET http://localhost:3000/servers/id:?
Content-Type: application/json
{

}
