# TRAZ TODOS OS USUÁRIOS
GET http://localhost:3000/users/
Content-Type: application/json

###
# INSERE NOVO USUÁRIO
PUT http://localhost:3000/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJsdWNhc0BzZXJ2aWNldHJpeC5jb20iLCJuYW1lIjoibHVjYXMiLCJpYXQiOjE2MTYwMjkwMjIsImV4cCI6MTYxNjAzOTgyMn0.pvQ1-Srznc-37it8JJlyDiaGITDShZCg08bpGRj0A5g
{
    "name": "eliabe",
    "email": "teste@servicetrix",
    "password": "12345"
}
###
# ALTERA UM USUÁRIO
PATCH  http://localhost:3000/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJsdWNhc0BzZXJ2aWNldHJpeC5jb20iLCJuYW1lIjoibHVjYXMiLCJpYXQiOjE2MTYwMjkwMjIsImV4cCI6MTYxNjAzOTgyMn0.pvQ1-Srznc-37it8JJlyDiaGITDShZCg08bpGRj0A5g
{
    "name": "eliabe Martins",
    "email": "martins@servicetrix",
    "password": "12345",
    "id" "?"
}
###
# DELETA UM USUÁRIO
DELETE http://localhost:3000/users/
Content-Type: application/json
{
    "id": "7"
}
###
# TRAZ DADOS DE UM USUÁRIO
GET http://localhost:3000/users/id:?
Content-Type: application/json
{

}
